version: '3.8'

services:
  app:
    build: .
    container_name: adminkit_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - mysql
      - redis
    networks:
      - adminkit
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=adminkit
      - DB_USERNAME=adminkit
      - DB_PASSWORD=adminkit123
      - REDIS_HOST=redis
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis

  nginx:
    image: nginx:alpine
    container_name: adminkit_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - adminkit

  mysql:
    image: mysql:8.0
    container_name: adminkit_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: adminkit
      MYSQL_USER: adminkit
      MYSQL_PASSWORD: adminkit123
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - adminkit
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: adminkit_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - adminkit

  mailhog:
    image: mailhog/mailhog
    container_name: adminkit_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - adminkit

  adminer:
    image: adminer
    container_name: adminkit_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - adminkit
    environment:
      ADMINER_DEFAULT_SERVER: mysql

networks:
  adminkit:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
